### PR TITLE
Update to 2020.2

### PR DESCRIPTION
**Pull request by emanuelbalea**

### CODE REVIEW

**Comment by emanuelbalea** [comment]
[configureawait_plugin.zip](https://github.com/aelij/ConfigureAwaitChecker/files/5105859/configureawait_plugin.zip)
Here is a test i have compiled for myself. Only tried Rider as that is all I have.

**Review by kamilbudziewski — APPROVED** [review]

**Comment by aelij** [comment]
Thanks for the fix :) Will publish it now

**Comment by emanuelbalea** [comment]
Anytime. Wonder if we can make it so that any 2020 version will work so we don’t t have to keep updating it. I doubt they will change the sdk to the point of breaking their plugins without a major version change. But I’m new to their sdk so not sure how to achieve that, if possible.

**Comment by yevgeniyredko** [comment]
@emanuelbalea no, because [ReSharper does not maintain](https://www.jetbrains.com/help/resharper/sdk/Extensions/PlatformVersioning.html) backwards binary compatibility between major or minor releases.

**Pull request merged**
