### PR TITLE
Update to 2020.1.0

### PR DESCRIPTION
**Pull request by yevgeniyredko**

### CODE REVIEW

**Comment by emanuelbalea** [comment]
HI @yevgeniyredko any chance you can send me a compiled rider plugin? I seem to have trouble compiling it myself on mac os. Many thanks in advance.

**Comment by yevgeniyredko** [comment]
@emanuelbalea 
[Arbel.Rider.ConfigureAwaitPlugin.zip](https://github.com/aelij/ConfigureAwaitChecker/files/4593369/Arbel.Rider.ConfigureAwaitPlugin.zip)

**Comment by emanuelbalea** [comment]
@yevgeniyredko you are awesome, thank you. you have no idea how used i got to having this plugin.

I wish i could figure out why it fails to load after successful compile and manual zip. unless im getting a false positive on the successful compile. But im not too familiar with the Rider plugin system.

**Comment by veton** [comment]
Made a changes and was about to create a PR, then found this thread :)
Thanks for that!

**Comment by aelij** [comment]
Please rebase onto master, I've merged the other PR which did some refactoring. And sorry for the delay :)

**Comment by yevgeniyredko** [comment]
@aelij rebased and made few changes. Now you can `dotnet pack` ReSharper plugin

**Comment by aelij** [comment]
Thanks for the fix! I'll publish it today (takes a bit to get approved by JB).

**Pull request merged**
