### PR TITLE
Update to 2018.3.0

### PR DESCRIPTION
**Pull request by yevgeniyredko**

### CODE REVIEW

**Comment by Socolin** [comment]
Could you also update META-INF/plugin.xml for Rider ?

`<idea-version since-build="183.5047.83" until-build="184.*"/>`

**Comment by matkoch** [comment]
Please use `183.*`. Otherwise it will be shown as compatible also for the next release, although it won’t be compatible.

**Comment by yevgeniyredko** [comment]
Yes, forgot about that. But `until-build` should be `183.*`

**Comment by DoCode** [comment]
Who can merge this and push to the JetBrains NuGet feed?

**Comment by aelij** [comment]
I'll push later today. Thanks, @yevgeniyredko!

**Comment by aelij** [comment]
Pushed

**Pull request merged**
